FROM ubuntu

#Install node
RUN apt-get update
RUN apt-get -y upgrade
RUN apt-get -y install npm 

# Expose port
EXPOSE 8080

# Install app dependencies
COPY package.json /app/
COPY package.json /root/

# Install app dependencies
RUN cd /app && \
    npm install

# Bundle app source
COPY . /app/
    
# Create app directory
WORKDIR /app/

# Start building project 
RUN npm run prod

# Start server
CMD [ "npm", "start" ]
